import { UserProfile } from "@/types";

export const DEMO_ACCOUNTS: Record<string, UserProfile> = {
  admin: {
    id: "staff_sarah_01",
    name: "Sarah Rotich",
    email: "admin@hotelkalya.com",
    phone: "+254 719 766649",
    role: "admin",
    staffRole: "ADMIN",
    department: "Executive Management",
    permissions: ["*"],
    createdAt: "2026-08-01T08:00:00Z",
  },
  receptionist: {
    id: "staff_dennis_01",
    name: "Dennis Kiplagat",
    email: "reception@hotelkalya.com",
    phone: "+254 712 998877",
    role: "staff",
    staffRole: "RECEPTIONIST",
    department: "Front Office",
    permissions: ["reservations:read", "reservations:write", "rooms:read", "rooms:write", "housekeeping:read"],
    createdAt: "2026-08-15T08:00:00Z",
  },
  housekeeping: {
    id: "staff_limo_01",
    name: "Denis Limo",
    email: "housekeeping@hotelkalya.com",
    phone: "+254 723 445566",
    role: "staff",
    staffRole: "HOUSEKEEPING",
    department: "Housekeeping",
    additionalDepartments: ["Events & Conferences"],
    permissions: ["rooms:read", "housekeeping:read", "housekeeping:write"],
    createdAt: "2026-08-20T08:00:00Z",
  },
  waiter: {
    id: "staff_faith_01",
    name: "Faith Jepchirchir",
    email: "waiter@hotelkalya.com",
    phone: "+254 734 556677",
    role: "staff",
    staffRole: "WAITER",
    department: "Food & Beverage",
    permissions: ["restaurant:orders"],
    createdAt: "2026-08-22T08:00:00Z",
  },
  chef: {
    id: "staff_patrick_01",
    name: "Chef Patrick Mwangi",
    email: "kitchen@hotelkalya.com",
    phone: "+254 745 667788",
    role: "staff",
    staffRole: "CHEF",
    department: "Kitchen Operations",
    permissions: ["restaurant:orders", "kitchen:kds"],
    createdAt: "2026-08-10T08:00:00Z",
  },
  event_coordinator: {
    id: "staff_kevin_01",
    name: "Kevin Lokor",
    email: "events@hotelkalya.com",
    phone: "+254 756 778899",
    role: "staff",
    staffRole: "EVENT_COORDINATOR",
    department: "Events & Conferences",
    permissions: ["conference:manage", "events:manage"],
    createdAt: "2026-08-18T08:00:00Z",
  },
  catering: {
    id: "staff_grace_01",
    name: "Grace Chepkorir",
    email: "catering@hotelkalya.com",
    phone: "+254 767 889900",
    role: "staff",
    staffRole: "CATERING_STAFF",
    department: "Outside Catering",
    permissions: ["catering:manage"],
    createdAt: "2026-08-25T08:00:00Z",
  },
  maintenance: {
    id: "staff_kipchumba_01",
    name: "John Kipchumba",
    email: "maintenance@hotelkalya.com",
    phone: "+254 778 112233",
    role: "staff",
    staffRole: "MAINTENANCE",
    department: "Engineering & Maintenance",
    permissions: ["rooms:read", "rooms:write", "housekeeping:read"],
    createdAt: "2026-08-05T08:00:00Z",
  },
  manager: {
    id: "staff_kimutai_01",
    name: "James Kimutai",
    email: "manager@hotelkalya.com",
    phone: "+254 789 223344",
    role: "staff",
    staffRole: "MANAGER",
    department: "Operations Management",
    permissions: [
      "reservations:read",
      "reservations:write",
      "rooms:read",
      "rooms:write",
      "housekeeping:read",
      "housekeeping:write",
      "restaurant:orders",
      "kitchen:kds",
      "conference:manage",
      "catering:manage",
      "events:manage",
      "reports:view",
      "staff:manage",
      "audit:view",
      "menu:manage",
      "inquiries:manage",
      "reviews:manage",
      "offers:manage",
      "gallery:manage",
      "announcements:manage",
      "airbnb:manage",
      "documents:manage",
    ],
    createdAt: "2026-08-01T08:00:00Z",
  },
  accountant: {
    id: "staff_rotich_acc_01",
    name: "Daniel Krop",
    email: "accounts@hotelkalya.com",
    phone: "+254 790 334455",
    role: "staff",
    staffRole: "ACCOUNTANT",
    department: "Finance & Accounts",
    permissions: ["reports:view", "reservations:read", "audit:view"],
    createdAt: "2026-08-03T08:00:00Z",
  },
  guest: {
    id: "user_kalya_demo_01",
    name: "James Chemosit",
    email: "guest@hotelkalya.com",
    phone: "+254 712 345678",
    role: "guest",
    dietaryPreferences: ["Halal", "Local Cuisine"],
    createdAt: "2026-09-01T10:00:00Z",
  },
};
