export interface ProjectDocMetadata {
  id: string;
  folder: string;
  filename: string;
  phaseNum: number;
  phaseName: string;
  title: string;
  category: "Onboarding" | "Proposal" | "Contract" | "Requirements" | "Content" | "Planning" | "Design" | "Development" | "QA" | "UAT" | "Deployment" | "Handover" | "Warranty" | "Closure";
  description: string;
  owner: string;
  lifecyclePhase: string;
  gate?: string;
}

export const PROJECT_DOCUMENTS: ProjectDocMetadata[] = [
  // 01-CLIENT-ONBOARDING
  {
    id: "DOC-001",
    folder: "01-CLIENT-ONBOARDING",
    filename: "DOC-001-Client-Intake-Form.md",
    phaseNum: 1,
    phaseName: "01 Client Onboarding",
    title: "Client Intake Form",
    category: "Onboarding",
    description: "Initial client intake capturing business model, decision makers, budget baseline, and core objectives.",
    owner: "Client Lead & Account Executive",
    lifecyclePhase: "Phase 01: Client Inquiry & Intake Form",
    gate: "Gate 1 (Pre-requisite)",
  },
  {
    id: "DOC-002",
    folder: "01-CLIENT-ONBOARDING",
    filename: "DOC-002-Discovery-Questionnaire.md",
    phaseNum: 1,
    phaseName: "01 Client Onboarding",
    title: "Discovery Questionnaire",
    category: "Onboarding",
    description: "Detailed brand discovery, target customer personas, operational workflows, and competitive landscape.",
    owner: "UX Researcher & Product Strategist",
    lifecyclePhase: "Phase 02: Discovery & Detailed Questionnaire",
    gate: "Gate 2 (Pre-requisite)",
  },
  {
    id: "DOC-003",
    folder: "01-CLIENT-ONBOARDING",
    filename: "DOC-003-Stakeholder-Matrix.md",
    phaseNum: 1,
    phaseName: "01 Client Onboarding",
    title: "Stakeholder Matrix & RACI",
    category: "Onboarding",
    description: "RACI governance defining who is Responsible, Accountable, Consulted, and Informed across every phase.",
    owner: "Project Manager",
    lifecyclePhase: "Phase 01: Client Onboarding Governance",
  },

  // 02-PROPOSAL
  {
    id: "DOC-004",
    folder: "02-PROPOSAL",
    filename: "DOC-004-Project-Proposal.md",
    phaseNum: 2,
    phaseName: "02 Proposal & Commercials",
    title: "Project Proposal",
    category: "Proposal",
    description: "Formal commercial and technical proposal outlining the end-to-end digital hospitality platform solution.",
    owner: "Technical Director",
    lifecyclePhase: "Phase 05: Formal Project Proposal",
    gate: "Gate 3 (Pre-requisite)",
  },
  {
    id: "DOC-005",
    folder: "02-PROPOSAL",
    filename: "DOC-005-Quotation.md",
    phaseNum: 2,
    phaseName: "02 Proposal & Commercials",
    title: "Commercial Quotation & Invoicing",
    category: "Proposal",
    description: "Itemized financial breakdown with milestone payment triggers (40% / 30% / 20% / 10%).",
    owner: "Finance & Accounts",
    lifecyclePhase: "Phase 06: Commercial Quotation & Tax Invoicing",
    gate: "Gate 4 (Pre-requisite)",
  },
  {
    id: "DOC-006",
    folder: "02-PROPOSAL",
    filename: "DOC-006-Scope-of-Work-SOW.md",
    phaseNum: 2,
    phaseName: "02 Proposal & Commercials",
    title: "Scope of Work (SOW)",
    category: "Proposal",
    description: "Strict project boundary definition detailing included vertical slices versus explicit out-of-scope items.",
    owner: "Solutions Architect",
    lifecyclePhase: "Phase 04: Scope of Work (SOW)",
    gate: "Gate 6 (Pre-requisite)",
  },

  // 03-CONTRACT
  {
    id: "DOC-007",
    folder: "03-CONTRACT",
    filename: "DOC-007-Development-Agreement.md",
    phaseNum: 3,
    phaseName: "03 Contract & Legal",
    title: "Development Agreement",
    category: "Contract",
    description: "Legally binding master software development contract with IP assignment, indemnities, and termination clauses.",
    owner: "Legal Counsel & Managing Director",
    lifecyclePhase: "Phase 07: Development Agreement & Sign-Off",
    gate: "Gate 5 (Pre-requisite)",
  },
  {
    id: "DOC-008",
    folder: "03-CONTRACT",
    filename: "DOC-008-Non-Disclosure-Agreement.md",
    phaseNum: 3,
    phaseName: "03 Contract & Legal",
    title: "Non-Disclosure Agreement (NDA)",
    category: "Contract",
    description: "Mutual confidentiality agreement safeguarding proprietary business data, trade secrets, and trade credentials.",
    owner: "Legal Counsel",
    lifecyclePhase: "Phase 07: NDA Execution",
  },
  {
    id: "DOC-009",
    folder: "03-CONTRACT",
    filename: "DOC-009-Terms-and-Conditions.md",
    phaseNum: 3,
    phaseName: "03 Contract & Legal",
    title: "Standard Terms & Conditions",
    category: "Contract",
    description: "Operational delivery terms, payment terms, delay protocols, force majeure, and warranty limitations.",
    owner: "Legal Counsel",
    lifecyclePhase: "Phase 07: Legal Sign-off",
  },

  // 04-REQUIREMENTS
  {
    id: "DOC-010",
    folder: "04-REQUIREMENTS",
    filename: "DOC-010-Software-Requirements-Specification-SRS.md",
    phaseNum: 4,
    phaseName: "04 Requirements & Architecture",
    title: "Software Requirements Specification (SRS)",
    category: "Requirements",
    description: "Formal IEEE-style engineering specification tagging functional and non-functional requirements (REQ-001 to REQ-050).",
    owner: "Lead Systems Architect",
    lifecyclePhase: "Phase 03: Requirements Specification (SRS)",
    gate: "Gate 7 (Pre-requisite)",
  },
  {
    id: "DOC-011",
    folder: "04-REQUIREMENTS",
    filename: "DOC-011-Feature-Matrix-MoSCoW.md",
    phaseNum: 4,
    phaseName: "04 Requirements & Architecture",
    title: "Feature Matrix & MoSCoW Prioritization",
    category: "Requirements",
    description: "MoSCoW prioritization defining Must-Have, Should-Have, Could-Have, and Won't-Have deliverables.",
    owner: "Product Manager",
    lifecyclePhase: "Phase 03: Feature Scoping",
  },
  {
    id: "DOC-012",
    folder: "04-REQUIREMENTS",
    filename: "DOC-012-User-Roles-Permissions-Matrix.md",
    phaseNum: 4,
    phaseName: "04 Requirements & Architecture",
    title: "User Roles & Permissions Matrix",
    category: "Requirements",
    description: "RBAC matrix covering Guests, Front Desk Staff, Kitchen / Chef team, and Admin Superusers.",
    owner: "Security Architect",
    lifecyclePhase: "Phase 12: User Roles & Permissions Matrix",
  },
  {
    id: "DOC-013",
    folder: "04-REQUIREMENTS",
    filename: "DOC-013-User-Flows-and-Journey-Maps.md",
    phaseNum: 4,
    phaseName: "04 Requirements & Architecture",
    title: "User Flows & Journey Maps",
    category: "Requirements",
    description: "Step-by-step user journeys for accommodation reservation, dining orders, conference inquiries, and admin check-in.",
    owner: "UX Designer",
    lifecyclePhase: "Phase 13: End-to-End User Flow Mapping",
  },
  {
    id: "DOC-014",
    folder: "04-REQUIREMENTS",
    filename: "DOC-014-Definition-of-Done.md",
    phaseNum: 4,
    phaseName: "04 Requirements & Architecture",
    title: "Definition of Done (DoD) & Acceptance Criteria",
    category: "Requirements",
    description: "Strict quality gates: 0 TypeScript errors, 100% responsive, SEO tags, unit verification, and client sign-off.",
    owner: "Lead QA Engineer",
    lifecyclePhase: "Phase 18: Quality Gates Definition",
  },

  // 05-CONTENT
  {
    id: "DOC-015",
    folder: "05-CONTENT",
    filename: "DOC-015-Content-Asset-Checklist.md",
    phaseNum: 5,
    phaseName: "05 Content & Brand Assets",
    title: "Content & Asset Checklist",
    category: "Content",
    description: "Audit and tracker of photography, hero imagery, menu pricing, room specs, and corporate copy.",
    owner: "Content Strategist",
    lifecyclePhase: "Phase 09: Content & Asset Collection",
    gate: "Gate 9 (Pre-requisite)",
  },
  {
    id: "DOC-016",
    folder: "05-CONTENT",
    filename: "DOC-016-Brand-Guidelines-Asset-Register.md",
    phaseNum: 5,
    phaseName: "05 Content & Brand Assets",
    title: "Brand Guidelines & Asset Register",
    category: "Content",
    description: "Brand tokens derived from physical flyer: Amber (#F2AE1C), Maroon (#7C1322), typography, and logo usage rules.",
    owner: "Brand Designer",
    lifecyclePhase: "Phase 09: Brand Identity Alignment",
  },
  {
    id: "DOC-017",
    folder: "05-CONTENT",
    filename: "DOC-017-Legal-and-Compliance-Audit.md",
    phaseNum: 5,
    phaseName: "05 Content & Brand Assets",
    title: "Legal & Compliance Audit",
    category: "Content",
    description: "Kenya Data Protection Act (KDPA 2019) compliance, Privacy Policy, Terms of Service, and cookie policies.",
    owner: "Compliance Officer",
    lifecyclePhase: "Phase 09: Regulatory Audit",
  },
  {
    id: "DOC-043",
    folder: "05-CONTENT",
    filename: "DOC-043-Technical-Access-Credentials-Delegation.md",
    phaseNum: 5,
    phaseName: "05 Content & Brand Assets",
    title: "Technical Access & Credentials Protocol",
    category: "Content",
    description: "Secure protocol for domain registrar delegation, Daraja M-Pesa API secrets, Google Cloud Maps keys, and Git access.",
    owner: "DevOps & Security Lead",
    lifecyclePhase: "Phase 10: Technical Access & Delegation Protocol",
  },
  {
    id: "DOC-044",
    folder: "05-CONTENT",
    filename: "DOC-044-Content-Approval-Sign-Off-Sheet.md",
    phaseNum: 5,
    phaseName: "05 Content & Brand Assets",
    title: "Content Approval & Sign-Off Sheet",
    category: "Content",
    description: "Formal editorial sign-off confirming room rates, dining menu pricing, conference capacities, and contact details.",
    owner: "Client Marketing Lead",
    lifecyclePhase: "Phase 19: Content Implementation & Data Verification",
  },

  // 06-PLANNING
  {
    id: "DOC-018",
    folder: "06-PLANNING",
    filename: "DOC-018-Information-Architecture-Sitemap.md",
    phaseNum: 6,
    phaseName: "06 Planning & IA",
    title: "Information Architecture & Sitemap",
    category: "Planning",
    description: "Canonical site hierarchy mapping all 49 distinct routes, URL taxonomy, breadcrumb trails, and SEO paths.",
    owner: "IA & SEO Architect",
    lifecyclePhase: "Phase 11: Information Architecture & Sitemap Approval",
    gate: "Gate 8 (Pre-requisite)",
  },
  {
    id: "DOC-019",
    folder: "06-PLANNING",
    filename: "DOC-019-Project-Schedule-WBS.md",
    phaseNum: 6,
    phaseName: "06 Planning & IA",
    title: "Project Schedule & Work Breakdown (WBS)",
    category: "Planning",
    description: "Six-week delivery schedule detailing milestone dates, sprint sprints, and delivery dependencies.",
    owner: "Project Manager",
    lifecyclePhase: "Phase 11: Timeline & Milestone Planning",
  },

  // 07-DESIGN
  {
    id: "DOC-020",
    folder: "07-DESIGN",
    filename: "DOC-020-Wireframe-Specification.md",
    phaseNum: 7,
    phaseName: "07 Design & UI/UX",
    title: "Wireframe Specification & Review",
    category: "Design",
    description: "Low and mid-fidelity wireframe layouts for desktop, tablet, and mobile breakpoints across all core pages.",
    owner: "UI/UX Designer",
    lifecyclePhase: "Phase 14: Structural Wireframing",
  },
  {
    id: "DOC-021",
    folder: "07-DESIGN",
    filename: "DOC-021-UI-Design-System.md",
    phaseNum: 7,
    phaseName: "07 Design & UI/UX",
    title: "UI Design System & Component Library",
    category: "Design",
    description: "Design system tokens: typography hierarchy, color scales, elevations, button states, and badge components.",
    owner: "Design System Lead",
    lifecyclePhase: "Phase 15: High-Fidelity UI/UX Design System",
  },
  {
    id: "DOC-022",
    folder: "07-DESIGN",
    filename: "DOC-022-Design-Freeze-Sign-Off.md",
    phaseNum: 7,
    phaseName: "07 Design & UI/UX",
    title: "Design Freeze & Client Sign-Off",
    category: "Design",
    description: "Milestone approval locking all visual layouts and design components prior to core code development.",
    owner: "Client Director & Lead Designer",
    lifecyclePhase: "Phase 16: Formal Design Sign-Off (Design Freeze Gate)",
    gate: "Gate 10 (Pre-requisite)",
  },

  // 08-DEVELOPMENT
  {
    id: "DOC-023",
    folder: "08-DEVELOPMENT",
    filename: "DOC-023-Technical-Architecture.md",
    phaseNum: 8,
    phaseName: "08 Development & Tech Stack",
    title: "Technical Architecture & Tech Stack",
    category: "Development",
    description: "Next.js App Router, React 19, Tailwind CSS v4, Lucide icons, state management, and edge hosting infrastructure.",
    owner: "Lead Systems Architect",
    lifecyclePhase: "Phase 17: Technical Architecture & Environment Setup",
  },
  {
    id: "DOC-024",
    folder: "08-DEVELOPMENT",
    filename: "DOC-024-Coding-Standards-Git-Workflow.md",
    phaseNum: 8,
    phaseName: "08 Development & Tech Stack",
    title: "Coding Standards & Git Workflow",
    category: "Development",
    description: "Strict TypeScript rules, vertical slices, conventional commits, branch protection, and linting policies.",
    owner: "Engineering Lead",
    lifecyclePhase: "Phase 17: Engineering Governance",
  },
  {
    id: "DOC-025",
    folder: "08-DEVELOPMENT",
    filename: "DOC-025-API-Specification.md",
    phaseNum: 8,
    phaseName: "08 Development & Tech Stack",
    title: "API Specification & Integration Contract",
    category: "Development",
    description: "OpenAPI/REST schemas for `/api/bookings`, `/api/orders`, `/api/payments/stk-push`, `/api/inquiries`.",
    owner: "Backend Lead",
    lifecyclePhase: "Phase 17: API Contract Definition",
  },

  // 09-QA
  {
    id: "DOC-026",
    folder: "09-QA",
    filename: "DOC-026-QA-Test-Plan-Traceability-Matrix.md",
    phaseNum: 9,
    phaseName: "09 Quality Assurance",
    title: "QA Test Plan & Traceability Matrix",
    category: "QA",
    description: "Test execution plan spanning cross-browser matrix, mobile responsiveness (375px/768px/1440px), and booking validation.",
    owner: "QA Lead",
    lifecyclePhase: "Phase 20: Internal Quality Assurance",
  },
  {
    id: "DOC-027",
    folder: "09-QA",
    filename: "DOC-027-Bug-Tracking-Defect-Log.md",
    phaseNum: 9,
    phaseName: "09 Quality Assurance",
    title: "Bug Tracking & Defect Severity Log",
    category: "QA",
    description: "Defect severity definitions (P1 Blockers to P4 Minor) and resolution tracking matrix.",
    owner: "QA Engineer",
    lifecyclePhase: "Phase 20: Bug Triaging",
  },
  {
    id: "DOC-028",
    folder: "09-QA",
    filename: "DOC-028-Security-OWASP-Compliance-Audit.md",
    phaseNum: 9,
    phaseName: "09 Quality Assurance",
    title: "Security, OWASP & SAIF Compliance Audit",
    category: "QA",
    description: "OWASP Top 10 vulnerabilities, Google SAIF compliance, CSP headers, XSS prevention, and secret management.",
    owner: "Security Auditor",
    lifecyclePhase: "Phase 25: Pre-Production Security & SAIF Audit",
  },
  {
    id: "DOC-045",
    folder: "09-QA",
    filename: "DOC-045-Change-Request-Impact-Assessment.md",
    phaseNum: 9,
    phaseName: "09 Quality Assurance",
    title: "Change Request Form & Impact Assessment",
    category: "QA",
    description: "Controlled change management protocol with cost, timeline, and architectural impact assessment.",
    owner: "Project Manager & Client Lead",
    lifecyclePhase: "Phase 23: Bug Triaging & Change Request Evaluation",
  },

  // 10-UAT
  {
    id: "DOC-029",
    folder: "10-UAT",
    filename: "DOC-029-UAT-Test-Script.md",
    phaseNum: 10,
    phaseName: "10 User Acceptance Testing",
    title: "UAT Test Script & Execution Scenarios",
    category: "UAT",
    description: "Client acceptance scenarios: room booking test, food ordering flow, contact submission, and admin dashboard review.",
    owner: "Client UAT Lead",
    lifecyclePhase: "Phase 22: Client User Acceptance Testing (UAT)",
  },
  {
    id: "DOC-030",
    folder: "10-UAT",
    filename: "DOC-030-UAT-Sign-Off-Certificate.md",
    phaseNum: 10,
    phaseName: "10 User Acceptance Testing",
    title: "Formal UAT Sign-Off Certificate",
    category: "UAT",
    description: "Formal client acceptance certificate unlocking Milestone 3 (20% payment release).",
    owner: "Client Director & Agency Lead",
    lifecyclePhase: "Phase 24: Formal UAT Sign-Off (20% Gate)",
  },

  // 11-DEPLOYMENT
  {
    id: "DOC-031",
    folder: "11-DEPLOYMENT",
    filename: "DOC-031-Pre-Production-Go-Live-Checklist.md",
    phaseNum: 11,
    phaseName: "11 Deployment & Go-Live",
    title: "Pre-Production & Go-Live Readiness Audit",
    category: "Deployment",
    description: "Comprehensive go-live checklist: SSL certificate, DNS TTL reduction, SEO sitemap submission, and analytics setup.",
    owner: "DevOps Lead",
    lifecyclePhase: "Phase 25: Pre-Production Security Audit",
  },
  {
    id: "DOC-032",
    folder: "11-DEPLOYMENT",
    filename: "DOC-032-Deployment-and-Rollback-Runbook.md",
    phaseNum: 11,
    phaseName: "11 Deployment & Go-Live",
    title: "Deployment & Rollback Runbook",
    category: "Deployment",
    description: "Step-by-step production cutover procedure, zero-downtime deployment steps, and immediate rollback protocol.",
    owner: "DevOps Engineer",
    lifecyclePhase: "Phase 26: Production Deployment & DNS Propagation",
  },
  {
    id: "DOC-033",
    folder: "11-DEPLOYMENT",
    filename: "DOC-033-Go-Live-Smoke-Test-Protocol.md",
    phaseNum: 11,
    phaseName: "11 Deployment & Go-Live",
    title: "Go-Live Smoke Test Protocol",
    category: "Deployment",
    description: "Post-deployment smoke testing: live SSL check, M-Pesa real 1 KES test transaction, and contact form verification.",
    owner: "QA & Operations Lead",
    lifecyclePhase: "Phase 27: Go-Live Smoke Testing Protocol",
  },

  // 12-HANDOVER
  {
    id: "DOC-034",
    folder: "12-HANDOVER",
    filename: "DOC-034-Project-Handover-Certificate.md",
    phaseNum: 12,
    phaseName: "12 Handover & Training",
    title: "Project Handover Certificate",
    category: "Handover",
    description: "Formal transfer of operational responsibility and intellectual property to Hotel Kalya management.",
    owner: "Agency Managing Director & Client CEO",
    lifecyclePhase: "Phase 29: Source Code & Account Handover",
  },
  {
    id: "DOC-035",
    folder: "12-HANDOVER",
    filename: "DOC-035-Maintenance-Operations-Manual.md",
    phaseNum: 12,
    phaseName: "12 Handover & Training",
    title: "Maintenance & Operations Manual",
    category: "Handover",
    description: "Operating instructions for menu updates, room rate adjustments, blog publishing, and backup management.",
    owner: "Lead Systems Architect",
    lifecyclePhase: "Phase 29: Handover Documentation",
  },
  {
    id: "DOC-036",
    folder: "12-HANDOVER",
    filename: "DOC-036-Admin-Staff-Training-Syllabus.md",
    phaseNum: 12,
    phaseName: "12 Handover & Training",
    title: "Admin & Staff Training Syllabus",
    category: "Handover",
    description: "Training modules for front desk receptionists, restaurant cashiers, and hotel managers.",
    owner: "Training Specialist",
    lifecyclePhase: "Phase 30: Staff Training Session",
  },
  {
    id: "DOC-037",
    folder: "12-HANDOVER",
    filename: "DOC-037-Repository-Credentials-Transfer.md",
    phaseNum: 12,
    phaseName: "12 Handover & Training",
    title: "Repository & Infrastructure Transfer Record",
    category: "Handover",
    description: "Formal audit and transfer of GitHub repository ownership, hosting accounts, and API credentials.",
    owner: "DevOps & Security Lead",
    lifecyclePhase: "Phase 29: Infrastructure Transfer",
  },

  // 13-WARRANTY
  {
    id: "DOC-038",
    folder: "13-WARRANTY",
    filename: "DOC-038-30-Day-Warranty-Protocol.md",
    phaseNum: 13,
    phaseName: "13 Warranty & Support",
    title: "30-Day Post-Launch Warranty Protocol",
    category: "Warranty",
    description: "Comprehensive 30-day bug warranty coverage terms, response times (1-4 hours for P1), and exclusion boundaries.",
    owner: "Support Manager",
    lifecyclePhase: "Phase 31: 30-Day Post-Launch Warranty Commencement",
  },
  {
    id: "DOC-039",
    folder: "13-WARRANTY",
    filename: "DOC-039-SLA-Maintenance-Agreement.md",
    phaseNum: 13,
    phaseName: "13 Warranty & Support",
    title: "SLA Maintenance & Support Agreement",
    category: "Warranty",
    description: "Ongoing monthly maintenance contract (Tier 1 / Tier 2 / Tier 3), uptime guarantee (99.9%), and security patch frequency.",
    owner: "Account Director & Client Lead",
    lifecyclePhase: "Phase 32: SLA Maintenance Contract Transition",
  },

  // 14-CLOSURE
  {
    id: "DOC-040",
    folder: "14-CLOSURE",
    filename: "DOC-040-Final-Acceptance-Certificate.md",
    phaseNum: 14,
    phaseName: "14 Project Closure",
    title: "Final Acceptance Certificate",
    category: "Closure",
    description: "Formal certification that all deliverables are completed, tested, and accepted without outstanding encumbrances.",
    owner: "Client CEO & Agency Managing Director",
    lifecyclePhase: "Phase 28: Final Payment & Formal Acceptance",
  },
  {
    id: "DOC-041",
    folder: "14-CLOSURE",
    filename: "DOC-041-Final-Settlement-Invoice.md",
    phaseNum: 14,
    phaseName: "14 Project Closure",
    title: "Final Settlement & Milestone Release",
    category: "Closure",
    description: "Final 10% payment invoice release, reconciliation of change requests, and full financial clearance.",
    owner: "Finance Director",
    lifecyclePhase: "Phase 28: Final Payment Settlement (10% Gate)",
  },
  {
    id: "DOC-042",
    folder: "14-CLOSURE",
    filename: "DOC-042-Project-Closure-Retrospective.md",
    phaseNum: 14,
    phaseName: "14 Project Closure",
    title: "Project Closure & Retrospective Report",
    category: "Closure",
    description: "Project closure retrospective, lessons learned, velocity analysis, and client testimonial authorization.",
    owner: "Project Delivery Team",
    lifecyclePhase: "Phase 32: Project Closure",
  },
];
